# Generated by Django 5.2.7 on 2025-10-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminsUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(db_column='email', max_length=100, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('can_create', models.BooleanField(blank=True, null=True)),
                ('can_update', models.BooleanField(blank=True, null=True)),
                ('can_read', models.BooleanField(blank=True, null=True)),
                ('can_delete', models.BooleanField(blank=True, null=True)),
                ('acc_status', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admins',
                'managed': False,
            },
        ),
    ]
