"""
Django settings for youth_welfare project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = []


#for deploy

# ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*', cast=lambda v: [s.strip() for s in v.split(',')])




AUTHENTICATION_BACKENDS = [
    'apps.accounts.auth_backends.AdminsBackend',
    'django.contrib.auth.backends.ModelBackend',  # keep default for Django superusers
]



AUTH_USER_MODEL = 'accounts.AdminsUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'rest_framework_simplejwt',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'youth_welfare',
    'apps.event',
    'corsheaders',
    #'drf_yasg',
    'apps.solidarity',
    'apps.family',
    'apps.accounts',
    'apps.accounts.schema',
]

MIDDLEWARE = [
    # 1. Security first
    'django.middleware.security.SecurityMiddleware',
    
    # 2. Session management
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # 3. CORS handling (before common middleware)
    'corsheaders.middleware.CorsMiddleware',
    
    # 4. Common utilities
    'django.middleware.common.CommonMiddleware',
    
    # 5. CSRF protection
    'django.middleware.csrf.CsrfViewMiddleware',
    
    # 6. Authentication
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    # 7. Messages framework
    'django.contrib.messages.middleware.MessageMiddleware',
    
    # 8. Clickjacking protection
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # 9. Your custom middleware (last)
    'apps.accounts.middleware.SecurityHeadersMiddleware',
    'apps.accounts.middleware.AuditLoggingMiddleware',
    'apps.accounts.middleware.RateLimitMiddleware',
]

# Cache Configuration for Rate Limiting
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'youth-welfare-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 10000
        }
    }
}

# For production, use Redis:
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }


# Security Headers
SECURE_BROWSER_XSS_FILTER = True
if DEBUG:
    # Development: Allow CDN resources
    SECURE_CONTENT_SECURITY_POLICY = {
        "default-src": ("'self'",),
        "script-src": (
            "'self'",
            "'unsafe-inline'",
            "https://cdn.jsdelivr.net",
            "https://cdnjs.cloudflare.com",
        ),
        "style-src": (
            "'self'",
            "'unsafe-inline'",
            "https://cdn.jsdelivr.net",
            "https://cdnjs.cloudflare.com",
        ),
        "img-src": ("'self'", "data:", "https:"),
        "font-src": ("'self'", "https://cdn.jsdelivr.net"),
    }
else:
    # Production: Stricter policy
    SECURE_CONTENT_SECURITY_POLICY = {
        "default-src": ("'self'",),
        "script-src": ("'self'",),
        "style-src": ("'self'", "'unsafe-inline'"),
    }

# CSRF Protection
CSRF_COOKIE_SECURE = not DEBUG  # True in production
CSRF_COOKIE_HTTPONLY = True
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='http://localhost:3000', cast=lambda v: [s.strip() for s in v.split(',')])

# Session Security
SESSION_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

# ============ RATE LIMITING CONFIGURATION ============

RATE_LIMIT_CONFIG = {
    # Authentication endpoints (strictest)
    'auth': {
        'max_requests': 200,        # 10 attempts per hour
        'window_seconds': 3600,
        'endpoints': [
            '/api/accounts/login/',
            '/api/accounts/auth/google/login/',
        ]
    },
    
    # Signup endpoints (strictest)
    'signup': {
        'max_requests': 500,         # 5 signups per hour
        'window_seconds': 3600,
        'endpoints': [
            '/api/accounts/signup/',
            '/api/accounts/auth/google/signup/',
        ]
    },
    
    # Read operations (most permissive)
    'read': {
        'max_requests': 200,       # 100 reads per hour
        'window_seconds': 3600,
        'endpoints': [
            '/api/accounts/profile/',
            '/api/accounts/admins/',
            '/api/solidarity/student/status/'



        ]
    },
    
    # Write operations (moderate)
    'write': {
        'max_requests': 30,        # 30 writes per hour
        'window_seconds': 3600,
        'endpoints': [
            '/api/accounts/profile/update_profile/',
        ]
    },
    
    # Default for all other endpoints
    'default': {
        'max_requests': 100,
        'window_seconds': 3600,
    }
}

# ===================================================
# ========================================



# ============ LOGGING ============

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'app.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'audit_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'audit.log'),
            'maxBytes': 1024 * 1024 * 50,  # 50MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'security.log'),
            'maxBytes': 1024 * 1024 * 20,  # 20MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'audit': {
            'handlers': ['audit_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'apps': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

# ================================

CORS_ALLOW_ALL_ORIGINS = True

# for deploy
# from decouple import Csv

# CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=False, cast=bool)
# CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='', cast=Csv())


"""
for media with front & back
"""

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




ROOT_URLCONF = 'youth_welfare.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'youth_welfare.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DATABASE_NAME'),
        'USER':  config('DATABASE_USER'),
        'PASSWORD': config('DATABASE_PASSWORD'),
        'HOST':  config('DATABASE_HOST'),
        'PORT': config('DATABASE_PORT', cast=int),
    }
}



# ============ ENCRYPTION SETTINGS ============
# AES Encryption Key for sensitive data at rest
ENCRYPTION_KEY = config('ENCRYPTION_KEY', default=None)

if not ENCRYPTION_KEY:
    raise ValueError(
        "ENCRYPTION_KEY not found in environment variables. "
        "Generate one using: from cryptography.fernet import Fernet; "
        "print(Fernet.generate_key().decode())"
    )

# Encrypted fields configuration
ENCRYPTED_FIELDS = {
    'Students': ['nid', 'uid', 'phone_number', 'address'],
}
# =============================================



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "apps.accounts.authentication.CustomJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}





###############################
SPECTACULAR_SETTINGS = {
    'TITLE': 'Youth Welfare API',
    'DESCRIPTION': 'API documentation for the Solidarity Subsystem',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,

    # ---- ONLY the name changed here ↓ -------------------------------
    'SECURITY_SCHEMES': {
        'Bearer': {                         #  <-- must be “Bearer”
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
        },
    },

    "SCHEMA_AUTHENTICATION_CLASSES": (
        "apps.accounts.authentication.CustomJWTAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayRequestDuration': True,
    },

    'SERVERS': [
        {
            'url': 'http://localhost:8000',
            'description': 'Local Development Server',
        },
        {
            'url': 'http://127.0.0.1:8000',
            'description': 'Local Development Server (127.0.0.1)',
        },
    ],
}
##################

# ============ GOOGLE OAUTH CONFIGURATION ============
from decouple import config

# Google OAuth Credentials (from .env file)
GOOGLE_CLIENT_ID = config('GOOGLE_OAUTH_CLIENT_ID', default=None)
GOOGLE_CLIENT_SECRET = config('GOOGLE_OAUTH_CLIENT_SECRET', default=None)
GOOGLE_REDIRECT_URI = config(
    'GOOGLE_OAUTH_REDIRECT_URI',
    default='http://localhost:3000/auth/google-callback'
)

GOOGLE_FRONTEND_CALLBACK_URL = "http://localhost:3000/auth/google-callback"

# Validate credentials are set
if not GOOGLE_CLIENT_ID or not GOOGLE_CLIENT_SECRET:
    import logging
    logger = logging.getLogger(__name__)
    logger.warning("⚠️ Google OAuth credentials not fully configured")

# Debug (development only)
if DEBUG:
    print(f"\n✓ Google OAuth Configuration Loaded:")
    print(f"  - Client ID: {GOOGLE_CLIENT_ID[:30] if GOOGLE_CLIENT_ID else 'NOT SET'}...")
    print(f"  - Redirect URI: {GOOGLE_REDIRECT_URI}\n")
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#####################################################
#to ignore migrations
MIGRATION_MODULES = {
    'event': None,
    'family': None,
    #'solidarity': None,
}



PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',          # ❬default❭
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',]


from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=150),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": config('SECRET_KEY'),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "admin_id",  # 👈 tell SimpleJWT which field to use
    "USER_ID_CLAIM": "admin_id",  # 👈 claim name in token
}

#"DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.AllowAny",)
# if i want to test whole apis once 

# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = '/media/'