# Generated by Django 5.2.7 on 2025-10-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.BinaryField()),
                ('role', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('can_create', models.BooleanField(blank=True, null=True)),
                ('can_update', models.BooleanField(blank=True, null=True)),
                ('can_read', models.BooleanField(blank=True, null=True)),
                ('can_delete', models.BooleanField(blank=True, null=True)),
                ('acc_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'faculties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_type', models.TextField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solidarities',
            fields=[
                ('solidarity_id', models.AutoField(primary_key=True, serialize=False)),
                ('req_status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('family_numbers', models.IntegerField()),
                ('father_status', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_status', models.CharField(blank=True, max_length=50, null=True)),
                ('father_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mother_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('arrange_of_brothers', models.IntegerField(blank=True, null=True)),
                ('m_phone_num', models.TextField(blank=True, null=True)),
                ('f_phone_num', models.TextField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('docs', models.CharField(blank=True, max_length=255, null=True)),
                ('disabilities', models.TextField(blank=True, null=True)),
                ('housing_status', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('acd_status', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solidarities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.BinaryField()),
                ('profile_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(max_length=1)),
                ('nid', models.TextField(unique=True)),
                ('uid', models.TextField(unique=True)),
                ('phone_number', models.TextField(unique=True)),
                ('address', models.CharField(max_length=255)),
                ('acd_year', models.CharField(max_length=50)),
                ('join_date', models.DateField()),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
