# Generated by Django 5.2.7 on 2025-11-10 21:08

import apps.solidarity.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('can_create', models.BooleanField(blank=True, null=True)),
                ('can_update', models.BooleanField(blank=True, null=True)),
                ('can_read', models.BooleanField(blank=True, null=True)),
                ('can_delete', models.BooleanField(blank=True, null=True)),
                ('acc_status', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('major', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField()),
                ('aff_discount', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, null=True, size=None)),
                ('reg_discount', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, null=True, size=None)),
                ('bk_discount', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, null=True, size=None)),
                ('full_discount', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, null=True, size=None)),
            ],
            options={
                'db_table': 'faculties',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('logged_at', models.DateTimeField(blank=True, null=True)),
                ('actor_type', models.TextField(blank=True, null=True)),
                ('target_type', models.TextField()),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solidarities',
            fields=[
                ('solidarity_id', models.AutoField(primary_key=True, serialize=False)),
                ('req_status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('family_numbers', models.IntegerField()),
                ('father_status', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_status', models.CharField(blank=True, max_length=50, null=True)),
                ('father_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mother_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('arrange_of_brothers', models.IntegerField(blank=True, null=True)),
                ('m_phone_num', models.TextField(blank=True, null=True)),
                ('f_phone_num', models.TextField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('disabilities', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('acd_status', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('req_type', models.TextField(blank=True, null=True)),
                ('housing_status', models.TextField(blank=True, null=True)),
                ('total_discount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'solidarities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField()),
                ('profile_photo', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(max_length=1)),
                ('nid', models.TextField(unique=True)),
                ('uid', models.TextField(unique=True)),
                ('phone_number', models.TextField(unique=True)),
                ('address', models.CharField(max_length=255)),
                ('acd_year', models.CharField(max_length=50)),
                ('join_date', models.DateField()),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('major', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolidarityDocs',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('بحث احتماعي', 'بحث احتماعي'), ('اثبات دخل', 'اثبات دخل'), ('ص.ب ولي امر', 'ص.ب ولي امر'), ('ص.ب شخصية', 'ص.ب شخصية'), ('حبازة زراعية', 'حبازة زراعية')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.solidarity.models.solidarity_doc_upload_path)),
                ('mime_type', models.CharField(max_length=80)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('solidarity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solidarity.solidarities')),
            ],
            options={
                'db_table': 'solidarity_docs',
                'managed': True,
                'unique_together': {('solidarity', 'doc_type')},
            },
        ),
    ]
