# Generated by Django 5.2.7 on 2025-11-09 20:18

import apps.solidarity.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solidarity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'departments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolidarityDocs',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('بحث احتماعي', 'بحث احتماعي'), ('اثبات دخل', 'اثبات دخل'), ('ص.ب ولي امر', 'ص.ب ولي امر'), ('ص.ب شخصية', 'ص.ب شخصية'), ('حبازة زراعية', 'حبازة زراعية')], max_length=50)),
                ('file', models.FileField(upload_to=apps.solidarity.models.solidarity_doc_upload_path)),
                ('mime_type', models.CharField(max_length=80)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('solidarity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='solidarity.solidarities')),
            ],
            options={
                'db_table': 'solidarity_docs',
                'managed': True,
                'unique_together': {('solidarity', 'doc_type')},
            },
        ),
    ]
