# Generated by Django 5.2.7 on 2025-11-09 20:43

import apps.solidarity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solidarity', '0002_departments_solidaritydocs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solidaritydocs',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.solidarity.models.solidarity_doc_upload_path),
        ),
    ]
